<a href="https://colab.research.google.com/github/VictorTobe/EEE540-assignment/blob/main/Tobe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import required libraries
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [ ]:
# Define a simple Perceptron model using TensorFlow
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3, activation='softmax', input_shape=(4,))
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=1, verbose=1)

Epoch 1/50
105/105 [==============================] - 1s 3ms/step - loss: 0.4604 - accuracy: 0.8381
Epoch 2/50
105/105 [==============================] - 0s 4ms/step - loss: 0.4399 - accuracy: 0.8381
Epoch 3/50
105/105 [==============================] - 0s 3ms/step - loss: 0.4228 - accuracy: 0.8476
Epoch 4/50
105/105 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8476
Epoch 5/50
105/105 [==============================] - 0s 2ms/step - loss: 0.3963 - accuracy: 0.8476
Epoch 6/50
105/105 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8476
Epoch 7/50
105/105 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8571
Epoch 8/50
105/105 [==============================] - 0s 2ms/step - loss: 0.3677 - accuracy: 0.8667
Epoch 9/50
105/105 [==============================] - 0s 2ms/step - loss: 0.3594 - accuracy: 0.8571
Epoch 10/50
105/105 [==============================] - 0s 1ms/step - loss: 0.3525 - accuracy: 0.8667

In [ ]:
# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=-1)

2/2 [==============================] - 0s 9ms/step


In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"Accuracy: {accuracy}")

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_classes)
print(f"Confusion Matrix:\n{conf_matrix}")


Accuracy: 0.9111111111111111
Confusion Matrix:
[[19  0  0]
 [ 0  9  4]
 [ 0  0 13]]
